"use client";
import React, { useEffect, useState } from "react";
import Link from "next/link";
import { ChevronRight, Database, GitPullRequest, Loader2, Play, RefreshCw, CheckCircle2, AlertTriangle, ExternalLink } from "lucide-react";
import { prStudioApi, PullRequest, ConnectedRepo } from "@/lib/pr-studio";
import { formatCurrency } from "@/lib/formatters";

export default function DemoPage() {
    const [repos, setRepos] = useState<ConnectedRepo[]>([]); const [repo, setRepo] = useState(""); const [prs, setPrs] = useState<PullRequest[]>([]); const [selected, setSelected] = useState<PullRequest | null>(null); const [files, setFiles] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [jobId, setJobId] = useState<string | null>(null); const [job, setJob] = useState<any | null>(null);
    async function loadRepos() { setLoading(true); setError(""); const r = await prStudioApi.getRepositories(); if (r.error) { setError(r.error.message) } else { const list = r.data?.repositories || []; setRepos(list); if (!repo && list[0]) setRepo(list[0].repository); } setLoading(false) }
    async function loadPRs(nextRepo = repo) { if (!nextRepo) return; setLoading(true); setError(""); const r = await prStudioApi.getPullRequests(nextRepo); if (r.error) setError(r.error.message); else setPrs(r.data?.pull_requests || []); setLoading(false); }
    async function selectPR(pr: PullRequest) { setSelected(pr); const r = await prStudioApi.getPullRequest(repo, pr.number); if (r.error) setError(r.error.message); else setFiles(r.data?.files || []); setJob(null); setJobId(null) }
    async function analyze() { if (!selected || !repo) return; setJob(null); setJobId(null); const r = await prStudioApi.analyze(repo, selected.number); if (r.error) { setError(r.error.message); return } setJobId(r.data!.job_id) }
    useEffect(() => { loadRepos() }, []); useEffect(() => { if (repo) loadPRs(repo) }, [repo]);
    useEffect(() => { if (!jobId) return; let stopped = false; const poll = async () => { const r = await prStudioApi.getJob(jobId); if (stopped) return; if (r.data) { setJob(r.data); if (["queued", "running"].includes(r.data.status)) { setTimeout(poll, 2000) } } else if (r.error) { setError(r.error.message) } }; poll(); return () => { stopped = true } }, [jobId]);
    return <div className="min-h-screen bg-slate-50 pb-20"><div className="bg-white border-b border-slate-200 sticky top-0 z-10"><div className="max-w-6xl mx-auto px-4 h-14 flex items-center justify-between"><div className="flex items-center gap-2 text-sm"><Link href="/" className="text-slate-500 hover:text-slate-900">Home</Link><ChevronRight className="size-3 text-slate-300" /><span className="font-semibold text-slate-900">PR Studio</span></div><Link href="/calculator" className="text-xs font-semibold text-slate-600 hover:text-slate-900">Cost Simulator →</Link></div></div>
        <div className="max-w-6xl mx-auto px-4 py-10"><div className="mb-8"><p className="text-xs font-mono uppercase tracking-widest text-orange-600">Live GitHub data</p><h1 className="text-3xl font-semibold mt-2">Review an actual pull request.</h1><p className="text-slate-500 mt-2 max-w-2xl">Choose a connected repository, inspect its current GitHub PR data, then run CostGate's real EXPLAIN-based analysis pipeline. Nothing on this page is a sample PR.</p></div>
            {error && <div className="mb-6 p-4 rounded-xl bg-rose-50 border border-rose-200 text-sm text-rose-700">{error}</div>}
            <div className="grid lg:grid-cols-12 gap-6"><section className="lg:col-span-4 bg-white border border-slate-200 rounded-2xl p-5 h-fit"><div className="flex items-center justify-between mb-4"><h2 className="text-sm font-bold">Connected repositories</h2><button onClick={loadRepos} className="text-slate-400 hover:text-slate-900"><RefreshCw className="size-4" /></button></div>{loading && repos.length === 0 ? <div className="py-8 flex justify-center"><Loader2 className="size-5 animate-spin text-orange-500" /></div> : repos.length === 0 ? <div className="text-sm text-slate-500">No repositories are connected. Complete onboarding first.</div> : <div className="space-y-2">{repos.map(r => <button key={r.repo_id} onClick={() => setRepo(r.repository)} className={`w-full text-left p-3 rounded-xl border ${repo === r.repository ? "border-orange-400 bg-orange-50" : "border-slate-200 hover:bg-slate-50"}`}><div className="flex items-center gap-2 text-sm font-semibold"><Database className="size-4 text-slate-400" />{r.repository}</div></button>)}</div>}</section>
                <section className="lg:col-span-8 space-y-5"><div className="bg-white border border-slate-200 rounded-2xl p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-bold">Open pull requests</h2><span className="text-xs text-slate-400">{prs.length} found</span></div>{loading && repo ? <div className="py-8 flex justify-center"><Loader2 className="size-5 animate-spin text-orange-500" /></div> : <div className="mt-4 space-y-2">{prs.map(pr => <button key={pr.number} onClick={() => selectPR(pr)} className={`w-full p-4 rounded-xl border text-left ${selected?.number === pr.number ? "border-slate-900 bg-slate-50" : "border-slate-200 hover:bg-slate-50"}`}><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-semibold text-slate-900">#{pr.number} {pr.title}</div><div className="mt-1 text-xs text-slate-500">{pr.user?.login || "unknown"} · {pr.base?.ref || "default"}</div></div><GitPullRequest className="size-4 text-slate-400 shrink-0" /></div></button>)}{!loading && repo && prs.length === 0 && <div className="py-8 text-sm text-slate-500 text-center">No open pull requests in this connected repository.</div>}</div>}</div>
                    {selected && <div className="bg-white border border-slate-200 rounded-2xl p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-mono text-orange-600">PR #{selected.number}</p><h2 className="text-xl font-semibold mt-1">{selected.title}</h2><p className="text-sm text-slate-500 mt-1">{repo}</p></div><div className="flex gap-2"><a href={selected.html_url} target="_blank" rel="noreferrer" className="px-3 py-2 border border-slate-200 rounded-lg text-xs font-semibold flex items-center gap-1">GitHub<ExternalLink className="size-3" /></a><button onClick={analyze} disabled={Boolean(jobId) || loading} className="px-3 py-2 bg-slate-900 text-white rounded-lg text-xs font-semibold flex items-center gap-1 disabled:opacity-50"><Play className="size-3" />{jobId ? "Analyzing…" : "Run CostGate analysis"}</button></div></div><div className="mt-5"><h3 className="text-xs font-mono uppercase tracking-widest text-slate-500 mb-2">Changed files</h3><div className="max-h-56 overflow-auto space-y-1">{files.map((f: any) => <div key={f.sha || f.filename} className="p-2.5 rounded-lg bg-slate-50 border border-slate-100 text-xs font-mono flex justify-between"><span>{f.filename}</span><span className="text-slate-400">+{f.additions || 0} -{f.deletions || 0}</span></div>)}</div></div></div>}
                    {job && <div className={`rounded-2xl border p-5 ${job.status === "succeeded" ? "bg-emerald-50 border-emerald-200" : "bg-white border-slate-200"}`}><div className="flex items-center gap-2 text-sm font-semibold">{job.status === "succeeded" ? <CheckCircle2 className="size-5 text-emerald-600" /> : job.status === "failed" ? <AlertTriangle className="size-5 text-rose-600" /> : <Loader2 className="size-5 animate-spin text-orange-500" />}Analysis {job.status}</div>{job.error && <p className="text-sm text-rose-700 mt-2">{job.error}</p>}{job.result && <div className="grid sm:grid-cols-3 gap-3 mt-4"><div className="bg-white/70 rounded-xl p-3 border border-slate-200"><div className="text-[11px] text-slate-500">Monthly delta</div><div className="text-lg font-mono font-bold">{formatCurrency(Number(job.result.monthly_delta || 0))}</div></div><div className="bg-white/70 rounded-xl p-3 border border-slate-200"><div className="text-[11px] text-slate-500">Confidence</div><div className="text-lg font-semibold capitalize">{job.result.confidence || "—"}</div></div><div className="bg-white/70 rounded-xl p-3 border border-slate-200"><div className="text-[11px] text-slate-500">Policy verdict</div><div className="text-lg font-semibold capitalize">{job.result.policy_verdict || "—"}</div></div></div>}</div>}
                </section></div></div></div>;
}
