"use client";
import React,{useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {CheckCircle2,Shield,ArrowLeft,Loader2} from "lucide-react";
import {StepAuth} from "@/components/onboarding/step-auth";
import {StepInstallRepo} from "@/components/onboarding/step-install-repo";
import {StepPolicyConfig} from "@/components/onboarding/step-policy-config";
const steps=[{number:1,title:"Connect GitHub"},{number:2,title:"Select repositories"},{number:3,title:"Configure policy"}];
export default function OnboardingPage(){const router=useRouter();const [step,setStep]=useState(1);const [user,setUser]=useState<any>(null);const [error,setError]=useState("");useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get("github_error"))setError("GitHub connection could not be completed. Start the connection again.");},[]);async function finish(policy:any){setError("");try{const res=await fetch("/api/dashboard/policy",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(policy)});const body=await res.json();if(!res.ok)throw new Error(body?.error?.message||"Could not save your policy.");router.push("/dashboard");router.refresh();}catch(e:any){setError(e.message||"Could not save your policy.")}}
return <div className="min-h-screen bg-slate-50 py-12 px-4"><div className="max-w-4xl mx-auto"><div className="flex items-center justify-between mb-8"><Link href="/" className="text-xs font-semibold text-slate-500 inline-flex items-center gap-2"><ArrowLeft className="size-3.5"/>Home</Link><span className="text-xs text-slate-400 font-mono flex items-center gap-1.5"><Shield className="size-3.5 text-emerald-500"/>Account-scoped setup</span></div><div className="mb-12 max-w-xl mx-auto"><div className="flex items-center justify-between relative"><div className="absolute left-0 right-0 top-4 h-px bg-slate-200 -z-0"/>{steps.map(s=><div key={s.number} className="flex flex-col items-center bg-slate-50 px-2 z-10"><div className={`size-8 rounded-full flex items-center justify-center text-xs font-mono font-bold ${step>s.number?"bg-emerald-500 text-white":step===s.number?"bg-orange-500 text-white ring-4 ring-orange-100":"bg-slate-200 text-slate-500"}`}>{step>s.number?<CheckCircle2 className="size-4"/>:s.number}</div><span className="text-[11px] mt-2 font-medium text-slate-500">{s.title}</span></div>)}</div></div>{error&&<div className="max-w-xl mx-auto mb-5 bg-rose-50 border border-rose-200 rounded-xl p-3 text-sm text-rose-700">{error}</div>}{step===1&&<StepAuth authenticatedUser={user} onComplete={u=>{setUser(u);setStep(2)}}/>}{step===2&&<StepInstallRepo onComplete={()=>setStep(3)}/>} {step===3&&<StepPolicyConfig onComplete={finish}/>}</div></div>}
