from __future__ import annotations

from decimal import Decimal

from app.domain.enums import ConfidenceLevel, CostDirection
from app.domain.models import AnalysisResult


class CostGateCommentRenderer:
    """
    Render an AnalysisResult as a GitHub PR comment.

    The renderer only presents values that already exist in AnalysisResult.
    It does not perform cost calculations or make new predictions.
    """

    def __init__(self, product_name: str = "CostGate") -> None:
        self.product_name = product_name

    def render(self, result: AnalysisResult) -> str:
        cost = result.cost_estimate
        comparison = result.comparison

        direction_icon = self._direction_icon(cost.direction)
        direction_text = self._direction_text(cost.direction)

        baseline_ms = result.baseline.execution_time_ms
        candidate_ms = result.candidate.execution_time_ms

        return "\n".join(
            [
                f"## {direction_icon} {self.product_name}",
                "",
                (
                    f"**Estimated monthly infrastructure impact:** "
                    f"{direction_text} **{self._usd(cost.monthly_delta)}**"
                ),
                "",
                (
                    f"**Confidence:** `{self._confidence(cost.confidence)}`"
                ),
                "",
                "### Query change",
                "",
                f"**File:** `{result.query.file_path}`",
                "",
                "```sql",
                f"-- Baseline",
                result.query.baseline_sql,
                "",
                f"-- Candidate",
                result.query.candidate_sql,
                "```",
                "",
                "### Execution impact",
                "",
                "| Metric | Baseline | Candidate |",
                "|---|---:|---:|",
                (
                    f"| Execution time | "
                    f"{baseline_ms:.3f} ms | "
                    f"{candidate_ms:.3f} ms |"
                ),
                (
                    f"| Scan type | "
                    f"`{result.baseline.scan_type.value}` | "
                    f"`{result.candidate.scan_type.value}` |"
                ),
                (
                    f"| Index used | "
                    f"{self._yes_no(result.baseline.index_used)} | "
                    f"{self._yes_no(result.candidate.index_used)} |"
                ),
                (
                    f"| Rows returned | "
                    f"{result.baseline.rows_returned} | "
                    f"{result.candidate.rows_returned} |"
                ),
                "",
                "### What changed",
                "",
                self._change_summary(result),
                "",
                "### Cost estimate",
                "",
                (
                    f"Estimated monthly impact: "
                    f"**{self._usd(cost.monthly_delta)}**"
                ),
                (
                    f"Estimated range: "
                    f"**{self._usd(cost.lower_bound)} – "
                    f"{self._usd(cost.upper_bound)}**"
                ),
                "",
                "This is an estimate of attributed database compute impact, "
                "not an AWS invoice prediction.",
                "",
                "### Assumptions",
                "",
                self._render_assumptions(cost.assumptions),
                "",
                "---",
                "",
                "_Generated by CostGate._",
            ]
        )

    @staticmethod
    def _usd(value: Decimal) -> str:
        return f"${value:,.2f}"

    @staticmethod
    def _yes_no(value: bool) -> str:
        return "Yes" if value else "No"

    @staticmethod
    def _direction_icon(direction: CostDirection) -> str:
        if direction is CostDirection.INCREASE:
            return "⚠️"

        if direction is CostDirection.DECREASE:
            return "✅"

        return "ℹ️"

    @staticmethod
    def _direction_text(direction: CostDirection) -> str:
        if direction is CostDirection.INCREASE:
            return "Increase of"

        if direction is CostDirection.DECREASE:
            return "Decrease of"

        return "No material change"

    @staticmethod
    def _confidence(confidence: ConfidenceLevel) -> str:
        return confidence.value

    @staticmethod
    def _change_summary(result: AnalysisResult) -> str:
        comparison = result.comparison

        parts: list[str] = []

        if comparison.scan_type_changed:
            parts.append(
                f"Scan changed from "
                f"`{result.baseline.scan_type.value}` to "
                f"`{result.candidate.scan_type.value}`."
            )

        if comparison.index_usage_changed:
            parts.append(
                f"Index usage changed from "
                f"`{CostGateCommentRenderer._yes_no(result.baseline.index_used)}` "
                f"to "
                f"`{CostGateCommentRenderer._yes_no(result.candidate.index_used)}`."
            )

        if comparison.execution_time_delta_ms != 0:
            ratio = comparison.execution_time_ratio

            if ratio > 1:
                parts.append(
                    f"Execution time increased by "
                    f"{comparison.execution_time_delta_ms:.3f} ms "
                    f"({ratio:.1f}×)."
                )
            else:
                parts.append(
                    f"Execution time changed by "
                    f"{comparison.execution_time_delta_ms:.3f} ms."
                )

        if comparison.shared_blocks_delta != 0:
            parts.append(
                f"Shared buffer blocks changed by "
                f"{comparison.shared_blocks_delta:,}."
            )

        if not parts:
            return "No material execution-plan difference was detected."

        return "\n".join(f"- {part}" for part in parts)

    @staticmethod
    def _render_assumptions(assumptions: dict) -> str:
        if not assumptions:
            return "_No additional assumptions recorded._"

        lines: list[str] = []

        for key, value in assumptions.items():
            label = key.replace("_", " ").title()

            if isinstance(value, float):
                rendered_value = f"{value:.4f}"
            else:
                rendered_value = str(value)

            lines.append(f"- **{label}:** `{rendered_value}`")

        return "\n".join(lines)