"use client";
import React, { useEffect, useState, useCallback, useRef } from "react";
import { Activity, TrendingUp, ShieldCheck, BarChart3, Layers, Users, Sliders, CheckCircle2 } from "lucide-react";
import { DashboardHeader } from "@/components/dashboard/dashboard-header";
import { RepoCard } from "@/components/dashboard/repo-card";
import { PRTable } from "@/components/dashboard/pr-table";
import { PRDetailModal } from "@/components/dashboard/pr-detail-modal";
import { TeamLeaderboard } from "@/components/dashboard/team-leaderboard";
import { PolicySettings } from "@/components/dashboard/policy-settings";
import { ErrorState } from "@/components/ui/error-state";
import { dashboardApi, DashboardPayload } from "@/lib/api/dashboard";
import { formatCurrency, formatNumber } from "@/lib/formatters";
import { cn } from "@/lib/utils";
export default function DashboardPage() {
    const [data, setData] = useState<DashboardPayload | null>(null); const [selectedRepoId, setSelectedRepoId] = useState("all"); const [tab, setTab] = useState<"prs" | "leaderboard" | "policy">("prs"); const [selected, setSelected] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<any>(null); const inflightRef = useRef(false);
    const load = useCallback(async () => { if (inflightRef.current) return; inflightRef.current = true; setLoading(true); setError(null); try { const res = await dashboardApi.getAll(); if (res.error) { setError(res.error); return } if (res.data) setData(res.data) } finally { setLoading(false); inflightRef.current = false } }, []);
    useEffect(() => { load() }, []);
    const repos = data?.repos || []; const repoFor = selectedRepoId === "all" ? null : repos.find(r => r.id === selectedRepoId); const predictions = (data?.predictions || []).filter(p => !repoFor || p.repository === repoFor.name); const summary = data?.summary; const authors = data?.authors || [];
    return <div className="min-h-screen bg-slate-50 text-slate-900 py-8 px-4"><div className="max-w-6xl mx-auto space-y-6"><DashboardHeader repos={repos} selectedRepoId={selectedRepoId} onSelectRepo={setSelectedRepoId} onRefresh={load} refreshing={loading} backendOnline={!error} />{error && <ErrorState error={error} onRetry={load} title="CostGate Backend API Error" />}<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">{[["Total PR Predictions", summary?.prediction_count, Activity, "text-orange-600"], ["Predicted Monthly Impact", summary ? formatCurrency(summary.total_predicted_monthly) : "—", TrendingUp, "text-amber-600"], ["Verified Actual Impact", summary ? formatCurrency(summary.total_verified_monthly) : "—", ShieldCheck, "text-emerald-600"], ["Mean Forecast Error", summary && summary.mean_error_pct != null ? `${summary.mean_error_pct.toFixed(2)}%` : "—", BarChart3, "text-sky-600"]].map(([label, value, Icon, color]: any) => <div key={label} className="p-4 rounded-md bg-white border border-slate-200 shadow-xs"><div className="flex items-center justify-between text-slate-500 text-[11px] font-mono font-medium uppercase"><span>{label}</span><Icon className={`size-3.5 ${color}`} /></div><div className="mt-3 text-2xl font-bold font-mono">{value ?? "—"}</div></div>)}</div>{repos.length > 0 && <div className="grid grid-cols-1 md:grid-cols-3 gap-3">{repos.map(r => <RepoCard key={r.id} repo={r} isSelected={selectedRepoId === r.id} onSelect={() => setSelectedRepoId(selectedRepoId === r.id ? "all" : r.id)} />)}</div>}<div className="flex items-center gap-1 border-b border-slate-200 pb-2"><button onClick={() => setTab("prs")} className={cn("px-3 py-1.5 rounded text-xs font-mono font-bold border", tab === "prs" ? "bg-slate-900 text-white border-slate-900" : "bg-white text-slate-600 border-slate-200")}><Layers className="inline size-3.5 mr-1" />PR History ({predictions.length})</button><button onClick={() => setTab("leaderboard")} className={cn("px-3 py-1.5 rounded text-xs font-mono font-bold border", tab === "leaderboard" ? "bg-slate-900 text-white border-slate-900" : "bg-white text-slate-600 border-slate-200")}><Users className="inline size-3.5 mr-1" />Developers ({authors.length})</button><button onClick={() => setTab("policy")} className={cn("px-3 py-1.5 rounded text-xs font-mono font-bold border", tab === "policy" ? "bg-slate-900 text-white border-slate-900" : "bg-white text-slate-600 border-slate-200")}><Sliders className="inline size-3.5 mr-1" />Policy</button></div>{tab === "prs" && <PRTable predictions={predictions} onSelectPrediction={setSelected} />} {tab === "leaderboard" && <TeamLeaderboard authors={authors} />} {tab === "policy" && <PolicySettings />}</div><PRDetailModal prediction={selected} onClose={() => setSelected(null)} /></div>
}
