"use client";
import React, { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Shield, CheckCircle2, ArrowRight, Loader2, ExternalLink } from "lucide-react";
import { GithubIcon } from "@/components/icons";
import { Logo } from "@/components/ui/logo";

interface StepAuthProps { onComplete: (user:{name:string;username:string;avatar:string})=>void; authenticatedUser:{name:string;username:string;avatar:string}|null; }
export function StepAuth({onComplete,authenticatedUser}:StepAuthProps){
 const [loading,setLoading]=useState(false); const [user,setUser]=useState(authenticatedUser); const [error,setError]=useState("");
 useEffect(()=>{ let active=true; fetch("/api/auth/session",{cache:"no-store"}).then(r=>r.json()).then(body=>{const u=body?.data?.user;if(active&&u){const mapped={name:u.name||u.github?.username||"CostGate user",username:u.github?.username||"",avatar:u.github?.avatar||""};setUser(mapped);if(mapped.username)onComplete(mapped);}}).catch(()=>{}); return ()=>{active=false}; },[]);
 const githubConnected=Boolean(user?.username);
 return <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="bg-white/80 backdrop-blur-xl border border-white/80 rounded-3xl p-8 sm:p-10 shadow-[0_8px_30px_rgb(0,0,0,0.04)] max-w-xl mx-auto"><div className="flex flex-col items-center text-center"><Logo size="lg" showText={false} className="mb-4"/><h2 className="text-2xl font-bold text-slate-900 tracking-tight">Connect your GitHub identity</h2><p className="text-sm text-slate-500 font-light mt-2 max-w-md">CostGate uses the GitHub App for repository access and GitHub OAuth only to identify and sign in the GitHub account you connect.</p>{githubConnected? <div className="w-full mt-8 p-4 rounded-2xl bg-emerald-50/80 border border-emerald-200/80 flex items-center justify-between"><div className="flex items-center gap-3">{user?.avatar&&<img src={user.avatar} alt={user.username} className="size-10 rounded-full border border-emerald-300"/>}<div className="text-left"><div className="text-xs font-mono text-emerald-800 font-bold">@{user?.username}</div><div className="text-[11px] text-emerald-600 flex items-center gap-1 font-medium"><CheckCircle2 className="size-3"/>GitHub account connected</div></div></div><button onClick={()=>onComplete(user!)} className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-semibold flex items-center gap-1.5"><span>Continue</span><ArrowRight className="size-3.5"/></button></div>:<div className="w-full mt-8 space-y-4">{error&&<p className="text-sm text-rose-600 bg-rose-50 border border-rose-100 rounded-xl p-3">{error}</p>}<button onClick={()=>{setLoading(true);setError("");window.location.href="/api/auth/github/login"}} disabled={loading} className="w-full py-3.5 px-6 rounded-2xl bg-slate-900 hover:bg-slate-800 text-white text-sm font-semibold flex items-center justify-center gap-3 transition-all shadow-md disabled:opacity-50">{loading?<Loader2 className="size-5 animate-spin"/>:<GithubIcon className="size-5 fill-current"/>}{loading?"Redirecting to GitHub…":"Connect GitHub"}</button><p className="text-xs text-slate-400 flex items-center justify-center gap-2"><Shield className="size-3.5 text-orange-500"/>OAuth identity + separate GitHub App repository permissions</p></div>}</div></motion.div>;
}
